### ISSUE TITLE
Project creation syntax error merge(...tasks)

### ISSUE THREAD

**Issue by pdemro** [codeBelt/boilerplate#4]
Running Git for Windows

trying slush project gives the error below.  Something does not like the ellipses syntax.

c:\users[user]\AppData\Roaming\npm\node_modules\slush-project\slush\tasks\scriptsBuildSystem\index.js:53
        return merge(...tasks);
                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\pdemro\AppData\Roaming\npm\node_modules\slush-project\slushfile.js:23:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by ccheney** [comment]
The ellipses is the [spread operator](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator)

Try upgrading your NodeJS version which has added es6 support
